export const CART_CONSTS = {
    ADD_TO_CART: "ADD_TO_CART",
    DELETE_ITEM : 'DELETE_ITEM',
    GET_TOTAL: "GET_TOTAL",
    INCREMENT_CART_NO: "INCREMENT_CART_NO",
    DECREMENT_CART_NO: "DECREMENT_CART_NO",
  };
  