export const CART_CONSTS = {
    ADD_TO_CART: "ADD_TO_CART",
    DELETE_ITEM : 'DELETE_ITEM',
    GET_TOTAL: "GET_TOTAL",
    INCREMENT_CART_NO: "INCREMENT_CART_NO",
    DECREMENT_CART_NO: "DECREMENT_CART_NO",
    GET_CART: "GET_CART",
    GET_CART_TOTAL: "GET_CART_TOTAL",
    REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
    UPDATE_CART_QUANTITY: "UPDATE_CART_QUANTITY",
    CALCULATE_TOTAL_WHEN_CHANGED: "CALCULATE_TOTAL_WHEN_CHANGED",
    GET_TOTAL_DEDUCT: "GET_TOTAL_DEDUCT"
  };
  