export const ProductActionTypes = {
    FETCH_PRODUCTS: "FETCH_PRODUCT",
    FILTER_PRODUCTS_BY_SIZE: "FILTER_PRODUCTS_BY_SIZE",
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  };
  