export const UserManageActionTypes = {
    FETCH_USERS: "FETCH_USERS",
    CREATE_USER:"CREATE_USER",
    DELETE_USER:"DELETE_USER",
    SELECTED_USER: "SELECTED_USER",
    REMOVE_SELECTED_USER: "REMOVE_SELECTED_USER",
  };
  