export const CART_CONSTS = {
    ADD_TO_CART : 'ADD_TO_CART',
    GET_TOTAL : 'GET_TOTAL',
    DELETE_ITEM : 'DELETE_ITEM',
    DECREMENT_CART : 'DECREMENT_CART',
    INCREMENT_CART_NO : 'INCREMENT_CART_NO',
    DECREMENT_CART_NO : 'DECREMENT_CART_NO',
    //GET_TOTAL_DEDUCT : 'GET_TOTAL_DEDUCT',

}